import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { api, backend, currentAdmin } from '../lib/backend'
import { Modal } from '../components/Modal'
import { Symbol } from '../components/BrandMark'

type Invite={id:string;code_hint:string;note:string;expires_at:string;status:string;used_email?:string;used_at?:string}
const labels:Record<string,string>={available:'可使用',used:'已使用',expired:'已过期',revoked:'已停用'}
export function InvitationsPage(){
 const cache=useQueryClient(),[page,setPage]=useState(0),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[create,setCreate]=useState(false),[count,setCount]=useState(5),[days,setDays]=useState(30),[note,setNote]=useState(''),[revoke,setRevoke]=useState<Invite|null>(null),[codes,setCodes]=useState<{code:string;expires_at:string;note:string}[]>([]),[copied,setCopied]=useState('')
 const who=useQuery({queryKey:['admin-me'],queryFn:currentAdmin}),allowed=['admin','super_admin'].includes(who.data?.role||'')
 const query=useQuery({queryKey:['admin-invites',page,status,search],enabled:allowed,queryFn:()=>backend?api.get('/admin/records?'+new URLSearchParams({kind:'invites',page:String(page),status,search})):{rows:[],total:0}})
 const mutation=useMutation({mutationFn:async(action:'create'|'revoke')=>action==='create'?api.rpc('admin_create_invitations',{count,days,note}):api.rpc('admin_revoke_invitation',{target_invitation:revoke!.id}),onSuccess:async(result,action)=>{if(action==='create'){setCodes(result);setCreate(false);setCopied('')}else setRevoke(null);await cache.invalidateQueries({queryKey:['admin-invites']});await cache.invalidateQueries({queryKey:['admin-overview']})}})
 const rows:Invite[]=query.data?.rows||[],total=query.data?.total||0
 return <>
  <div className="page-header"><div><div className="eyebrow">INVITATION / ACCESS</div><h1>邀请码</h1><p className="muted">每个邀请码仅能注册一个账号，可设置有效期并随时停用。</p></div><button className="pill-button primary" disabled={!backend||!allowed} onClick={()=>{mutation.reset();setCreate(true)}}><Symbol>add</Symbol>生成邀请码</button></div>
  {!backend&&<p className="muted">本地预览；连接后端后可以管理邀请码。</p>}
  <div className="info-banner"><Symbol>key</Symbol><span><strong>从一份邀请开始。</strong> 每码限一人，完整邀请码仅在生成时显示，请及时复制或下载保存。</span></div>
  {who.data&&!allowed&&<p role="alert">邀请码仅限管理员管理，请联系管理员开通权限。</p>}
  <div className="filters"><label className="search-field glass"><Symbol>search</Symbol><input aria-label="搜索邀请码" placeholder="搜索备注、尾号或注册邮箱" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><select className="pill-button" aria-label="邀请码状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">全部状态</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="pill-button" onClick={()=>void query.refetch()} disabled={query.isFetching}>刷新</button></div>
  {(query.error||who.error)&&<p className="error-bar" role="alert">{(query.error||who.error)?.message}</p>}
  <div className="invite-grid">{rows.map(row=><article className="panel glass strong invite-card" key={row.id}><div className="invite-card-top"><strong>•••• {row.code_hint}</strong><span className={`badge ${row.status==='available'?'ok':row.status==='used'?'':'warn'}`}>{labels[row.status]}</span></div><div className="invite-card-body"><h3>{row.note||'未填写备注'}</h3><p>有效期至 {new Date(row.expires_at).toLocaleString('zh-CN')}</p>{row.used_at&&<p>{row.used_email||'账号已删除'}<br/>{new Date(row.used_at).toLocaleString('zh-CN')} 注册</p>}<div className="invite-card-bottom"><small>单次使用 · 一人一码</small><button className="pill-button" disabled={row.status!=='available'} onClick={()=>{mutation.reset();setRevoke(row)}}>停用</button></div></div></article>)}</div>
  {query.isLoading&&<div className="loading-state" role="status" aria-label="正在读取邀请码"><div className="skeleton"/><div className="skeleton"/></div>}
  {!query.isLoading&&allowed&&!rows.length&&!query.error&&<div className="empty-state panel glass strong"><Symbol>key</Symbol><strong>{search||status?'没有匹配的邀请码':'为第一批伙伴，发出邀请'}</strong><p>{search||status?'调整关键词或状态，查找其他邀请记录。':'生成邀请码，复制给你想邀请的人。注册后可以在这里查看使用记录。'}</p>{search||status?<button className="pill-button" onClick={()=>{setSearch('');setStatus('');setPage(0)}}>清除筛选</button>:<button className="pill-button" disabled={!backend} onClick={()=>{mutation.reset();setCreate(true)}}><Symbol>add</Symbol>生成第一批邀请码</button>}</div>}
  <div className="pagination"><span>共 {total} 个 · 第 {page+1} 页</span><button className="pill-button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</button><button className="pill-button" disabled={(page+1)*25>=total} onClick={()=>setPage(p=>p+1)}>下一页</button></div>
  {create&&<Modal title="生成邀请码" busy={mutation.isPending} onClose={()=>setCreate(false)}><form onSubmit={e=>{e.preventDefault();mutation.mutate('create')}}><label className="field"><span>数量（每码限一人）</span><input type="number" min={1} max={50} required value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label className="field"><span>有效天数</span><input type="number" min={1} max={365} required value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label className="field"><span>备注 / 邀请批次</span><input maxLength={200} value={note} onChange={e=>setNote(e.target.value)}/></label>{mutation.error&&<p role="alert" className="error-text">{mutation.error.message}</p>}<button className="pill-button primary" disabled={mutation.isPending}>{mutation.isPending?'正在生成…':'生成并查看'}</button></form></Modal>}
  {codes.length>0&&<Modal title="邀请码已生成" onClose={()=>setCodes([])}><p>完整邀请码仅在这里显示，请先复制保存。关闭后只能查看尾号和使用记录。</p><textarea className="invite-codes" aria-label="新生成的邀请码" readOnly rows={Math.min(10,codes.length+1)} value={codes.map(c=>c.code).join('\n')}/><button className="pill-button primary" onClick={async()=>{try{await navigator.clipboard.writeText(codes.map(c=>c.code).join('\n'));setCopied('已复制')}catch{setCopied('复制失败，请选中文本手动复制。')}}}>复制全部</button><span role="status">{copied}</span><button className="pill-button" onClick={()=>{const blob=new Blob([codes.map(c=>`${c.code}\t${c.expires_at}\t${c.note.replace(/[\r\n\t]/g,' ')}`).join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='邀请码.txt';a.click();URL.revokeObjectURL(url)}}>下载保存</button></Modal>}
  {revoke&&<Modal title="停用邀请码" busy={mutation.isPending} onClose={()=>setRevoke(null)}><p>停用尾号 {revoke.code_hint} 的邀请码后，它将无法注册账号。</p>{mutation.error&&<p role="alert" className="error-text">{mutation.error.message}</p>}<button className="pill-button primary" disabled={mutation.isPending} onClick={()=>mutation.mutate('revoke')}>{mutation.isPending?'正在停用…':'确认停用'}</button></Modal>}
 </>
}
